### ISSUE TITLE
Translate slash command description

### ISSUE THREAD

**Issue by ShimadaNanaki** [giorgi-o/SkinPeek#108]
Hello.
Thanks for maintaining such a great project.
I would like to translate the description section of Slash Commands, do you have any plans to change the code for this?

**Comment by giorgi-o** [comment]
Unfortunately not :(
Although the discord.js library allows this, it would require a restructuring of the slash commands code in the bot. I'll probably get around to it eventually, once I'm less busy IRL.

However for your own self-hosted bot, you can just open bot.js and translate them there!
If you see any errors after doing so, it might be because discord has pretty strict limits on how long the command names and descriptions can be.
And if they don't change after you restarted the bot, you may need to re-deploy the commands (instructions in the README).

If you have any other questions, feel free to ask!

**Comment by ShimadaNanaki** [comment]
Okay, I will help with the translation again when it is implemented!
