### ISSUE TITLE
Deploy Guild not working

### ISSUE THREAD

**Issue by Its-Tachanks** [giorgi-o/SkinPeek#11]
Whenever I run "!deploy guild", it gives me an error of 
```js
C:\Users\user\OneDrive\Documents\GitHub\SkinPeek\node_modules\discord.js\src\rest\RequestHandler.js:350
      throw new DiscordAPIError(data, res.status, request);
            ^

DiscordAPIError: Missing Access
```
If I use !deploy global, it doesnt throw any errors and says "Deployed Globally" by the bot, but has never actually made any slash commands work

Yes, the bot has admin within my server

**Comment by giorgi-o** [comment]
There are two problems here:
- The `DiscordAPIError: Missing Access` means you didn't invite the bot with the `application.commands` scope. Kick it and invite it again with the correct scope when you generate the invite URL.
- The global commands take up to an hour to propagate to all guilds due to Discord aggressively caching commands.
