### ISSUE TITLE
Third Party Authentication

### ISSUE THREAD

**Issue by pmetemp** [giorgi-o/SkinPeek#62]
Apologies for opening an unrelated topic, since I have no other way to contact you.
I've read your comments on Riot blocking third-party authentication due to Valorant account cracking and was wondering if there have been any solutions found so far.
I'm trying to secure an upcoming name for my main account but this tool no longer works [cactus](https://github.com/3SUM/cactus)
![Screenshot_1](https://user-images.githubusercontent.com/85654852/202574249-69246686-3fa8-48cc-a32d-18c7d9b390b2.png)
Perhaps logging into the game client and submitting requests rather than logging in through the tool would work?

**Comment by giorgi-o** [comment]
There have been solutions, in fact if you look at auth.js you should see most of them. Unfortunately they all require modifying the code. Not familiar with cactus, but it seems to have not been updated since May, so unless you or another generous person is willing to do the necessary modifications, you're probably out of luck.
You can always try asking for help here: https://discord.gg/a9yzrw3KAm
