### ISSUE TITLE
Alerts aren't working

### ISSUE THREAD

**Issue by cxnsonance** [giorgi-o/SkinPeek#79]
Hello, I recently added the bot to my server and it's not showing alerts for skins that have came into the shop.

I used the command /testalerts and it tells me everything should be working.

What might the cause be?

**Comment by giorgi-o** [comment]
Are you talking about Ministral? Keep in mind that it only checks for alerts at 8AM UTC (8h after shop reset) because it tends to get rate limited at midnight, when everyone else is fighting to see their shop. It then takes a few hours to go check the alerts of all users of the bot.

If you still didn't get the alert, add me on discord `Giorgio#0609` and I'll personally look into it :)

**Comment by cxnsonance** [comment]
Sweet! Thank you c:
